version: '3'

services:
  pinjur-lunch-app:
    image: pinjur-lunch:stable
    container_name: pinjur-lunch-stable
    working_dir: /app
    ports:
      ## Expose the port depending on the chosen port [default port: 80]
      - "80:80"
    command:
      -mongo mongodb://mongo-db:27017
    depends_on:
      - mongo-db
  mongo-db:
    container_name: "pinjur-mongo-db-stable"
    image: mongo:4
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
